variables:
 KUBE_CONTEXT: "gitlab-examples/ops/gitops-demo/k8s-agents:demo-agent"

deploy:
   image:
     name: bitnami/kubectl:latest
     entrypoint: [""]
   script:
     - kubectl config get-contexts 
