name: Test_Migration8270811/hello-world-service
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  dast_environment_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      KUBE_INGRESS_BASE_DOMAIN: 74.220.23.215.nip.io
      KUBE_NAMESPACE: demo-agent
      TEST_DISABLED: 'true'
      CODE_QUALITY_DISABLED: 'true'
      LICENSE_MANAGEMENT_DISABLED: 'true'
      BROWSER_PERFORMANCE_DISABLED: 'true'
      LOAD_PERFORMANCE_DISABLED: 'true'
      SAST_DISABLED: 'true'
      SECRET_DETECTION_DISABLED: 'true'
      DEPENDENCY_SCANNING_DISABLED: 'true'
      CONTAINER_SCANNING_DISABLED: 'true'
      DAST_DISABLED: 'true'
      REVIEW_DISABLED: 'true'
      CODE_INTELLIGENCE_DISABLED: 'true'
      CLUSTER_IMAGE_SCANNING_DISABLED: 'true'
      POSTGRES_ENABLED: 'false'
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - uses: actions/download-artifact@v4.1.0
      with:
        name: build
